changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - enhancement
        - feature
        - semver-minor
    - title: Bug Fixes
      labels:
        - bug
        - fix
        - semver-patch
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
